import { DataSource, Repository } from 'typeorm';
import { Logger } from '@nestjs/common';
import { ServiceProfile, ServiceType, ProfileName } from '../../service-profiles/entities/service-profile.entity';

export class SeedServiceProfiles {
  private readonly logger = new Logger(SeedServiceProfiles.name);

  async run(dataSource: DataSource): Promise<void> {
    const serviceProfileRepository = dataSource.getRepository(ServiceProfile);

    // Check if service profiles already exist
    const existingProfiles = await serviceProfileRepository.count();
    if (existingProfiles > 0) {
      this.logger.log(`Found ${existingProfiles} existing service profiles, skipping seed`);
      return;
    }

    this.logger.log('Seeding service profiles...');

    const serviceProfiles = [
      // Cleaning Services - BHK based pricing
      {
        serviceType: ServiceType.CLEANING,
        profileName: ProfileName.BHK_1,
        description: 'Basic home cleaning for 1 BHK - dusting, sweeping, mopping',
        scopeDefinition: 'Living areas and bedrooms',
        maxCapacityHint: '2 visits per day',
        monthlyPrice: 1999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.CLEANING,
        profileName: ProfileName.BHK_2,
        description: 'Standard cleaning for 2 BHK with bathroom and kitchen',
        scopeDefinition: 'Full home except deep cleaning',
        maxCapacityHint: '1 visit per day',
        monthlyPrice: 2999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.CLEANING,
        profileName: ProfileName.BHK_3,
        description: 'Extended cleaning for 3 BHK with weekly deep clean',
        scopeDefinition: 'Full home with weekly deep cleaning',
        maxCapacityHint: '2 visits per day',
        monthlyPrice: 3999,
        visitpattern: 'DAILY',
        maxvisitsperday: 2,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Cooking Services - Person count + Meal plan based pricing
      // Person 1
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_1_BF,
        description: 'Cooking for 1 person - Breakfast Only',
        scopeDefinition: 'Breakfast Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 1299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_1_LUNCH,
        description: 'Cooking for 1 person - Lunch Only',
        scopeDefinition: 'Lunch Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 1599,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_1_DINNER,
        description: 'Cooking for 1 person - Dinner Only',
        scopeDefinition: 'Dinner Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 1599,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_1_BF_LUNCH,
        description: 'Cooking for 1 person - Breakfast + Lunch',
        scopeDefinition: 'Breakfast + Lunch',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 2599,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_1_LUNCH_DINNER,
        description: 'Cooking for 1 person - Lunch + Dinner',
        scopeDefinition: 'Lunch + Dinner',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 2899,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon', 'evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_1_FULL_DAY,
        description: 'Cooking for 1 person - Full Day (3 meals)',
        scopeDefinition: 'Breakfast + Lunch + Dinner',
        maxCapacityHint: '3 meals daily',
        monthlyPrice: 4499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Person 2
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_2_BF,
        description: 'Cooking for 2 persons - Breakfast Only',
        scopeDefinition: 'Breakfast Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 1999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_2_LUNCH,
        description: 'Cooking for 2 persons - Lunch Only',
        scopeDefinition: 'Lunch Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 2499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_2_DINNER,
        description: 'Cooking for 2 persons - Dinner Only',
        scopeDefinition: 'Dinner Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 2499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_2_BF_LUNCH,
        description: 'Cooking for 2 persons - Breakfast + Lunch',
        scopeDefinition: 'Breakfast + Lunch',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 3999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_2_LUNCH_DINNER,
        description: 'Cooking for 2 persons - Lunch + Dinner',
        scopeDefinition: 'Lunch + Dinner',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 4499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon', 'evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_2_FULL_DAY,
        description: 'Cooking for 2 persons - Full Day (3 meals)',
        scopeDefinition: 'Breakfast + Lunch + Dinner',
        maxCapacityHint: '3 meals daily',
        monthlyPrice: 6999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Person 3
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_3_BF,
        description: 'Cooking for 3 persons - Breakfast Only',
        scopeDefinition: 'Breakfast Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 2599,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_3_LUNCH,
        description: 'Cooking for 3 persons - Lunch Only',
        scopeDefinition: 'Lunch Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 3299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_3_DINNER,
        description: 'Cooking for 3 persons - Dinner Only',
        scopeDefinition: 'Dinner Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 3299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_3_BF_LUNCH,
        description: 'Cooking for 3 persons - Breakfast + Lunch',
        scopeDefinition: 'Breakfast + Lunch',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 5299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_3_LUNCH_DINNER,
        description: 'Cooking for 3 persons - Lunch + Dinner',
        scopeDefinition: 'Lunch + Dinner',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 5999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon', 'evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_3_FULL_DAY,
        description: 'Cooking for 3 persons - Full Day (3 meals)',
        scopeDefinition: 'Breakfast + Lunch + Dinner',
        maxCapacityHint: '3 meals daily',
        monthlyPrice: 9299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Person 4
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_4_BF,
        description: 'Cooking for 4 persons - Breakfast Only',
        scopeDefinition: 'Breakfast Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 3199,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_4_LUNCH,
        description: 'Cooking for 4 persons - Lunch Only',
        scopeDefinition: 'Lunch Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 3999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
profileName: ProfileName.BHK_4_DINNER,
         description: 'Cooking for 4 persons - Dinner Only',
        scopeDefinition: 'Dinner Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 3999,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_4_BF_LUNCH,
        description: 'Cooking for 4 persons - Breakfast + Lunch',
        scopeDefinition: 'Breakfast + Lunch',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 6499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_4_LUNCH_DINNER,
        description: 'Cooking for 4 persons - Lunch + Dinner',
        scopeDefinition: 'Lunch + Dinner',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 7299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon', 'evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_4_FULL_DAY,
        description: 'Cooking for 4 persons - Full Day (3 meals)',
        scopeDefinition: 'Breakfast + Lunch + Dinner',
        maxCapacityHint: '3 meals daily',
        monthlyPrice: 11499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Person 5
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_5_BF,
        description: 'Cooking for 5 persons - Breakfast Only',
        scopeDefinition: 'Breakfast Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 3699,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_5_LUNCH,
        description: 'Cooking for 5 persons - Lunch Only',
        scopeDefinition: 'Lunch Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 4699,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_5_DINNER,
        description: 'Cooking for 5 persons - Dinner Only',
        scopeDefinition: 'Dinner Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 4699,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_5_BF_LUNCH,
        description: 'Cooking for 5 persons - Breakfast + Lunch',
        scopeDefinition: 'Breakfast + Lunch',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 7499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_5_LUNCH_DINNER,
        description: 'Cooking for 5 persons - Lunch + Dinner',
        scopeDefinition: 'Lunch + Dinner',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 8499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon', 'evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_5_FULL_DAY,
        description: 'Cooking for 5 persons - Full Day (3 meals)',
        scopeDefinition: 'Breakfast + Lunch + Dinner',
        maxCapacityHint: '3 meals daily',
        monthlyPrice: 13499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Person 6
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_6_BF,
        description: 'Cooking for 6 persons - Breakfast Only',
        scopeDefinition: 'Breakfast Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 4199,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_6_LUNCH,
        description: 'Cooking for 6 persons - Lunch Only',
        scopeDefinition: 'Lunch Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 5299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_6_DINNER,
        description: 'Cooking for 6 persons - Dinner Only',
        scopeDefinition: 'Dinner Only',
        maxCapacityHint: '1 meal daily',
        monthlyPrice: 5299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_6_BF_LUNCH,
        description: 'Cooking for 6 persons - Breakfast + Lunch',
        scopeDefinition: 'Breakfast + Lunch',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 8499,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_6_LUNCH_DINNER,
        description: 'Cooking for 6 persons - Lunch + Dinner',
        scopeDefinition: 'Lunch + Dinner',
        maxCapacityHint: '2 meals daily',
        monthlyPrice: 9599,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['afternoon', 'evening'],
        isActive: true,
      },
      {
        serviceType: ServiceType.COOK,
        profileName: ProfileName.BHK_6_FULL_DAY,
        description: 'Cooking for 6 persons - Full Day (3 meals)',
        scopeDefinition: 'Breakfast + Lunch + Dinner',
        maxCapacityHint: '3 meals daily',
        monthlyPrice: 15299,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
      // Maid Services
      {
        serviceType: ServiceType.MAID,
        profileName: ProfileName.BASIC,
        description: 'Basic maid service - 4 hours daily',
        scopeDefinition: 'Light household chores',
        maxCapacityHint: '4 hours per day',
        monthlyPrice: 3500,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.MAID,
        profileName: ProfileName.STANDARD,
        description: 'Standard maid service - 8 hours daily',
        scopeDefinition: 'Full household management',
        maxCapacityHint: '8 hours per day',
        monthlyPrice: 6000,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon'],
        isActive: true,
      },
      {
        serviceType: ServiceType.MAID,
        profileName: ProfileName.EXTENDED,
        description: 'Extended maid service with cooking',
        scopeDefinition: 'Full household + cooking duties',
        maxCapacityHint: '10 hours per day',
        monthlyPrice: 9000,
        visitpattern: 'DAILY',
        maxvisitsperday: 1,
        defaulttimewindows: ['morning', 'afternoon', 'evening'],
        isActive: true,
      },
    ];

    for (const profileData of serviceProfiles) {
      const profile = serviceProfileRepository.create({
        ...profileData,
        publicId: require('crypto').randomUUID(),
      });
      await serviceProfileRepository.save(profile);
      this.logger.log(`Created service profile: ${profile.serviceType} - ${profile.profileName}`);
    }

    this.logger.log(`Seeded ${serviceProfiles.length} service profiles`);
    await this.verifySeedData(serviceProfileRepository);
  }

  private async verifySeedData(
    serviceProfileRepository: Repository<ServiceProfile>,
  ): Promise<void> {
    const profiles = await serviceProfileRepository.find();
    this.logger.log(`Verification: Found ${profiles.length} service profiles in database`);
    
    if (profiles.length === 0) {
      this.logger.error('WARNING: No service profiles found after seeding!');
    } else {
      this.logger.log('Service profile seeding completed successfully');
    }
  }
}
