// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqqcSlnym-IQIrZQsp2Zkk1iDenO-oQg',
    appId: '1:787166049871:web:5374c26588514b0ac81c3a',
    messagingSenderId: '787166049871',
    projectId: 'sevaq-6fcc4',
    authDomain: 'sevaq-6fcc4.firebaseapp.com',
    storageBucket: 'sevaq-6fcc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqqcSlnym-IQIrZQsp2Zkk1iDenO-oQg',
    appId: '1:787166049871:android:5374c26588514b0ac81c3a',
    messagingSenderId: '787166049871',
    projectId: 'sevaq-6fcc4',
    storageBucket: 'sevaq-6fcc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvqqcSlnym-IQIrZQsp2Zkk1iDenO-oQg',
    appId: '1:787166049871:ios:5374c26588514b0ac81c3a',
    messagingSenderId: '787166049871',
    projectId: 'sevaq-6fcc4',
    storageBucket: 'sevaq-6fcc4.firebasestorage.app',
    iosBundleId: 'com.sevaq.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvqqcSlnym-IQIrZQsp2Zkk1iDenO-oQg',
    appId: '1:787166049871:macos:5374c26588514b0ac81c3a',
    messagingSenderId: '787166049871',
    projectId: 'sevaq-6fcc4',
    storageBucket: 'sevaq-6fcc4.firebasestorage.app',
    iosBundleId: 'com.sevaq.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvqqcSlnym-IQIrZQsp2Zkk1iDenO-oQg',
    appId: '1:787166049871:web:5374c26588514b0ac81c3a',
    messagingSenderId: '787166049871',
    projectId: 'sevaq-6fcc4',
    authDomain: 'sevaq-6fcc4.firebaseapp.com',
    storageBucket: 'sevaq-6fcc4.firebasestorage.app',
  );
}
